In [1]:
import numpy as np

In [66]:
pred = np.array([
    [0,0,0,0],
    [0,1,1,0],
    [0,1,1,0],
    [2,2,2,2]
])
pred

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [2, 2, 2, 2]])

In [82]:
def one_shot_masks(pred):
    '''
    Input:    2D matrix of n_H x n_W containing label-ids as entries
    Output:   3D matrix of n_Unique_Labels x n_H x n_W containing masks at each 0th-axis 
    '''
    
    uniq_labels = np.unique(pred)
    n_pred_rows, n_pred_cols = pred.shape
    one_shot_tensor = np.zeros((len(uniq_labels), n_pred_rows, n_pred_cols))
    one_shot_tensor = one_shot_tensor.astype(np.int)
    
    for i in range(len(uniq_labels)):
        label_val = uniq_labels[i]
        temp_mask = pred == label_val
        temp_mask = temp_mask * 1
        one_shot_tensor[i,:,:] = temp_mask
        
    return one_shot_tensor

In [85]:
one_shot_masks(pred)

array([[[1, 1, 1, 1],
        [1, 0, 0, 1],
        [1, 0, 0, 1],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 1, 1, 0],
        [0, 1, 1, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 1, 1, 1]]])

In [87]:
np.argmax(one_shot_masks(pred),0)

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [2, 2, 2, 2]])